import { User, JobApplication, NetworkContact, DailyGoal } from '../types';

export const mockUser: User = {
  id: '1',
  name: 'John Doe',
  email: 'john@example.com',
  currentEducation: 'M.Tech Final Semester, BITS Pilani WILP',
  germanLevel: 'B1',
  currentRole: 'Independent Contractor (Part-time)',
  points: 247,
  level: 2,
  levelName: 'Active Applicant',
  currentStreak: 7,
  longestStreak: 12,
  createdAt: new Date().toISOString(),
};

export const mockApplications: JobApplication[] = [
  {
    id: '1',
    userId: '1',
    companyName: 'SAP',
    positionTitle: 'Full Stack Developer',
    location: 'Berlin',
    jobUrl: 'https://linkedin.com/jobs/123',
    salaryRange: '60000-80000',
    techStack: 'React, Python, PostgreSQL',
    status: 'Phone Screen',
    visaSponsorship: true,
    germanRequirement: 'Basic',
    relocationSupport: true,
    jobBoardSource: 'LinkedIn',
    priorityStars: 5,
    notes: 'Great company culture',
    appliedDate: '2025-01-15',
    createdAt: '2025-01-15T10:00:00Z',
    updatedAt: '2025-01-18T14:30:00Z',
  },
  {
    id: '2',
    userId: '1',
    companyName: 'Siemens',
    positionTitle: 'Backend Engineer',
    location: 'Munich',
    jobUrl: 'https://linkedin.com/jobs/456',
    salaryRange: '65000-85000',
    techStack: 'Python, Django, Docker',
    status: 'Applied',
    visaSponsorship: true,
    germanRequirement: 'None',
    relocationSupport: false,
    jobBoardSource: 'StepStone',
    priorityStars: 4,
    appliedDate: '2025-01-18',
    createdAt: '2025-01-18T09:00:00Z',
    updatedAt: '2025-01-18T09:00:00Z',
  },
  {
    id: '3',
    userId: '1',
    companyName: 'BMW',
    positionTitle: 'Software Developer',
    location: 'Munich',
    jobUrl: 'https://xing.com/jobs/789',
    salaryRange: '70000-90000',
    techStack: 'Java, Spring, Kubernetes',
    status: 'Technical Round 1',
    visaSponsorship: true,
    germanRequirement: 'Fluent',
    relocationSupport: true,
    jobBoardSource: 'Xing',
    priorityStars: 5,
    notes: 'Passed initial screening, technical interview scheduled',
    appliedDate: '2025-01-10',
    createdAt: '2025-01-10T14:30:00Z',
    updatedAt: '2025-01-16T11:45:00Z',
  },
  {
    id: '4',
    userId: '1',
    companyName: 'Zalando',
    positionTitle: 'Frontend Developer',
    location: 'Berlin',
    jobUrl: 'https://company-website.com/careers/101',
    salaryRange: '55000-75000',
    techStack: 'React, TypeScript, Next.js',
    status: 'Replied',
    visaSponsorship: false,
    germanRequirement: 'Basic',
    relocationSupport: false,
    jobBoardSource: 'Company Website',
    priorityStars: 3,
    notes: 'Received response, phone screen next week',
    appliedDate: '2025-01-12',
    createdAt: '2025-01-12T10:15:00Z',
    updatedAt: '2025-01-17T09:20:00Z',
  },
  {
    id: '5',
    userId: '1',
    companyName: 'Deutsche Bank',
    positionTitle: 'Data Engineer',
    location: 'Frankfurt',
    jobUrl: 'https://stepstone.de/jobs/202',
    salaryRange: '65000-85000',
    techStack: 'Python, Spark, Airflow',
    status: 'Rejected',
    visaSponsorship: true,
    germanRequirement: 'None',
    relocationSupport: false,
    jobBoardSource: 'StepStone',
    priorityStars: 4,
    notes: 'Good technical fit but location not ideal',
    appliedDate: '2025-01-08',
    createdAt: '2025-01-08T10:00:00Z',
    updatedAt: '2025-01-18T14:00:00Z',
  },
  {
    id: '6',
    userId: '1',
    companyName: 'Volkswagen',
    positionTitle: 'Full Stack Developer',
    location: 'Wolfsburg',
    jobUrl: 'https://xing.com/jobs/303',
    salaryRange: '55000-75000',
    techStack: 'React, Node.js, MongoDB',
    status: 'Technical Round 2',
    visaSponsorship: false,
    germanRequirement: 'Basic',
    relocationSupport: true,
    jobBoardSource: 'Xing',
    priorityStars: 3,
    notes: 'Passed technical round 1, final interview coming up',
    appliedDate: '2025-01-05',
    createdAt: '2025-01-05T11:30:00Z',
    updatedAt: '2025-01-20T09:15:00Z',
  },
  {
    id: '7',
    userId: '1',
    companyName: 'E.ON',
    positionTitle: 'DevOps Engineer',
    location: 'Essen',
    jobUrl: 'https://indeed.de/jobs/404',
    salaryRange: '60000-80000',
    techStack: 'Kubernetes, Docker, AWS',
    status: 'Phone Screen',
    visaSponsorship: true,
    germanRequirement: 'None',
    relocationSupport: false,
    jobBoardSource: 'Indeed',
    priorityStars: 4,
    notes: 'Phone screen scheduled for next week',
    appliedDate: '2025-01-12',
    createdAt: '2025-01-12T14:20:00Z',
    updatedAt: '2025-01-16T16:45:00Z',
  },
  {
    id: '8',
    userId: '1',
    companyName: 'Telekom',
    positionTitle: 'Backend Developer',
    location: 'Bonn',
    jobUrl: 'https://company-website.com/careers/505',
    salaryRange: '58000-78000',
    techStack: 'Java, Spring Boot, PostgreSQL',
    status: 'Applied',
    visaSponsorship: true,
    germanRequirement: 'Basic',
    relocationSupport: true,
    jobBoardSource: 'Company Website',
    priorityStars: 5,
    notes: 'Applied through company website, great benefits package',
    appliedDate: '2025-01-20',
    createdAt: '2025-01-20T08:30:00Z',
    updatedAt: '2025-01-20T08:30:00Z',
  },
  {
    id: '9',
    userId: '1',
    companyName: 'Bosch',
    positionTitle: 'Software Engineer',
    location: 'Stuttgart',
    jobUrl: 'https://linkedin.com/jobs/606',
    salaryRange: '62000-82000',
    techStack: 'C++, Qt, Embedded Systems',
    status: 'Final Round',
    visaSponsorship: true,
    germanRequirement: 'Fluent',
    relocationSupport: true,
    jobBoardSource: 'LinkedIn',
    priorityStars: 5,
    notes: 'Final interview with CTO scheduled for next week',
    appliedDate: '2024-12-15',
    createdAt: '2024-12-15T13:45:00Z',
    updatedAt: '2025-01-18T11:20:00Z',
  },
  {
    id: '10',
    userId: '1',
    companyName: 'Merck',
    positionTitle: 'Data Scientist',
    location: 'Darmstadt',
    jobUrl: 'https://xing.com/jobs/707',
    salaryRange: '65000-85000',
    techStack: 'Python, TensorFlow, SQL',
    status: 'Offer',
    visaSponsorship: true,
    germanRequirement: 'None',
    relocationSupport: false,
    jobBoardSource: 'Xing',
    priorityStars: 4,
    notes: 'Received offer! Currently in negotiation phase.',
    appliedDate: '2024-12-20',
    createdAt: '2024-12-20T10:15:00Z',
    updatedAt: '2025-01-22T10:45:00Z',
  },
];

export const mockContacts: NetworkContact[] = [
  {
    id: '1',
    userId: '1',
    name: 'Rajesh Kumar',
    email: 'rajesh@example.com',
    company: 'SAP',
    relationship: 'Former colleague',
    connectionStrength: 5,
    lastContactDate: '2025-01-10',
    notes: 'Can provide referral for full-stack positions. Very supportive and well-connected in the Berlin tech scene.',
  },
  {
    id: '2',
    userId: '1',
    name: 'Anna Schmidt',
    email: 'anna.schmidt@siemens.com',
    company: 'Siemens',
    relationship: 'LinkedIn Connection',
    connectionStrength: 4,
    lastContactDate: '2025-01-15',
    notes: 'HR Manager at Siemens Munich. Reached out about backend developer positions.',
    applicationId: '2'
  },
  {
    id: '3',
    userId: '1',
    name: 'Michael Weber',
    email: 'michael.weber@google.com',
    company: 'Google',
    relationship: 'Mentor',
    connectionStrength: 5,
    lastContactDate: '2024-12-20',
    notes: 'Senior engineer at Google Munich. Provides excellent career advice and interview tips.',
  },
  {
    id: '4',
    userId: '1',
    name: 'Lisa Mueller',
    email: 'lisa.mueller@startup.de',
    company: 'TechStartup GmbH',
    relationship: 'Conference Contact',
    connectionStrength: 3,
    lastContactDate: '2024-11-28',
    notes: 'Met at WebDev Conference Berlin 2024. Interested in junior developers with German skills.',
  },
  {
    id: '5',
    userId: '1',
    name: 'Thomas Bauer',
    email: 'thomas.bauer@bmw.de',
    company: 'BMW',
    relationship: 'Alumni',
    connectionStrength: 4,
    lastContactDate: '2025-01-05',
    notes: 'BITS Pilani alumni working in automotive software. Can help with networking in Munich.',
  },
  {
    id: '6',
    userId: '1',
    name: 'Sarah Johnson',
    company: 'Microsoft',
    relationship: 'Current Colleague',
    connectionStrength: 4,
    lastContactDate: '2025-01-18',
    notes: 'Works in the same team. Great for internal referrals and technical discussions.',
  },
  {
    id: '7',
    userId: '1',
    name: 'David Chen',
    email: 'david.chen@freelancer.net',
    relationship: 'Industry Contact',
    connectionStrength: 2,
    lastContactDate: '2024-10-15',
    notes: 'Freelance developer. Occasional project collaborations. Not very active on LinkedIn.',
  },
  {
    id: '8',
    userId: '1',
    name: 'Maria Garcia',
    email: 'maria.garcia@telekom.de',
    company: 'Deutsche Telekom',
    relationship: 'Referral Source',
    connectionStrength: 4,
    lastContactDate: '2024-12-10',
    notes: 'Provided referral for a position at Telekom. Very helpful and responsive.',
    applicationId: '1'
  },
];

export const mockDailyGoals: DailyGoal[] = [
  {
    id: '1',
    userId: '1',
    date: new Date().toISOString().split('T')[0],
    goalType: 'Apply to jobs',
    targetCount: 5,
    currentCount: 3,
    completed: false,
  },
  {
    id: '2',
    userId: '1',
    date: new Date().toISOString().split('T')[0],
    goalType: 'Follow up on applications',
    targetCount: 3,
    currentCount: 1,
    completed: false,
  },
  {
    id: '3',
    userId: '1',
    date: new Date().toISOString().split('T')[0],
    goalType: 'Add networking contacts',
    targetCount: 2,
    currentCount: 2,
    completed: true,
  },
];