import { User, JobApplication, NetworkContact, DailyGoal } from '../types';

export const mockUser: User = {
  id: '1',
  name: 'John Doe',
  email: 'john@example.com',
  currentEducation: 'M.Tech Final Semester, BITS Pilani WILP',
  germanLevel: 'B1',
  currentRole: 'Independent Contractor (Part-time)',
  points: 247,
  level: 2,
  levelName: 'Active Applicant',
  currentStreak: 7,
  longestStreak: 12,
  createdAt: new Date().toISOString(),
};

export const mockApplications: JobApplication[] = [
  // Recent applications (2025)
  {
    id: '1',
    userId: '1',
    companyName: 'SAP',
    positionTitle: 'Full Stack Developer',
    location: 'Berlin',
    jobUrl: 'https://linkedin.com/jobs/123',
    salaryRange: '60000-80000',
    techStack: 'React, Python, PostgreSQL',
    status: 'Phone Screen',
    visaSponsorship: true,
    germanRequirement: 'Basic',
    relocationSupport: true,
    jobBoardSource: 'LinkedIn',
    priorityStars: 5,
    notes: 'Great company culture',
    appliedDate: '2025-01-15',
    createdAt: '2025-01-15T10:00:00Z',
    updatedAt: '2025-01-18T14:30:00Z',
  },
  {
    id: '2',
    userId: '1',
    companyName: 'Siemens',
    positionTitle: 'Backend Engineer',
    location: 'Munich',
    jobUrl: 'https://linkedin.com/jobs/456',
    salaryRange: '65000-85000',
    techStack: 'Python, Django, Docker',
    status: 'Applied',
    visaSponsorship: true,
    germanRequirement: 'None',
    relocationSupport: false,
    jobBoardSource: 'StepStone',
    priorityStars: 4,
    appliedDate: '2025-01-18',
    createdAt: '2025-01-18T09:00:00Z',
    updatedAt: '2025-01-18T09:00:00Z',
  },
  {
    id: '3',
    userId: '1',
    companyName: 'BMW',
    positionTitle: 'Software Developer',
    location: 'Munich',
    jobUrl: 'https://xing.com/jobs/789',
    salaryRange: '70000-90000',
    techStack: 'Java, Spring, Kubernetes',
    status: 'Technical Round 1',
    visaSponsorship: true,
    germanRequirement: 'Fluent',
    relocationSupport: true,
    jobBoardSource: 'Xing',
    priorityStars: 5,
    notes: 'Passed initial screening, technical interview scheduled',
    appliedDate: '2025-01-10',
    createdAt: '2025-01-10T14:30:00Z',
    updatedAt: '2025-01-16T11:45:00Z',
  },
  {
    id: '4',
    userId: '1',
    companyName: 'Zalando',
    positionTitle: 'Frontend Developer',
    location: 'Berlin',
    jobUrl: 'https://company-website.com/careers/101',
    salaryRange: '55000-75000',
    techStack: 'React, TypeScript, Next.js',
    status: 'Replied',
    visaSponsorship: false,
    germanRequirement: 'Basic',
    relocationSupport: false,
    jobBoardSource: 'Company Website',
    priorityStars: 3,
    notes: 'Received response, phone screen next week',
    appliedDate: '2025-01-12',
    createdAt: '2025-01-12T10:15:00Z',
    updatedAt: '2025-01-17T09:20:00Z',
  },
  {
    id: '5',
    userId: '1',
    companyName: 'Deutsche Bank',
    positionTitle: 'Data Engineer',
    location: 'Frankfurt',
    jobUrl: 'https://stepstone.de/jobs/202',
    salaryRange: '65000-85000',
    techStack: 'Python, Spark, Airflow',
    status: 'Rejected',
    visaSponsorship: true,
    germanRequirement: 'None',
    relocationSupport: false,
    jobBoardSource: 'StepStone',
    priorityStars: 4,
    notes: 'Good technical fit but location not ideal',
    appliedDate: '2025-01-08',
    createdAt: '2025-01-08T10:00:00Z',
    updatedAt: '2025-01-18T14:00:00Z',
  },
  {
    id: '6',
    userId: '1',
    companyName: 'Volkswagen',
    positionTitle: 'Full Stack Developer',
    location: 'Wolfsburg',
    jobUrl: 'https://xing.com/jobs/303',
    salaryRange: '55000-75000',
    techStack: 'React, Node.js, MongoDB',
    status: 'Technical Round 2',
    visaSponsorship: false,
    germanRequirement: 'Basic',
    relocationSupport: true,
    jobBoardSource: 'Xing',
    priorityStars: 3,
    notes: 'Passed technical round 1, final interview coming up',
    appliedDate: '2025-01-05',
    createdAt: '2025-01-05T11:30:00Z',
    updatedAt: '2025-01-20T09:15:00Z',
  },
  {
    id: '7',
    userId: '1',
    companyName: 'E.ON',
    positionTitle: 'DevOps Engineer',
    location: 'Essen',
    jobUrl: 'https://indeed.de/jobs/404',
    salaryRange: '60000-80000',
    techStack: 'Kubernetes, Docker, AWS',
    status: 'Phone Screen',
    visaSponsorship: true,
    germanRequirement: 'None',
    relocationSupport: false,
    jobBoardSource: 'Indeed',
    priorityStars: 4,
    notes: 'Phone screen scheduled for next week',
    appliedDate: '2025-01-12',
    createdAt: '2025-01-12T14:20:00Z',
    updatedAt: '2025-01-16T16:45:00Z',
  },
  {
    id: '8',
    userId: '1',
    companyName: 'Telekom',
    positionTitle: 'Backend Developer',
    location: 'Bonn',
    jobUrl: 'https://company-website.com/careers/505',
    salaryRange: '58000-78000',
    techStack: 'Java, Spring Boot, PostgreSQL',
    status: 'Applied',
    visaSponsorship: true,
    germanRequirement: 'Basic',
    relocationSupport: true,
    jobBoardSource: 'Company Website',
    priorityStars: 5,
    notes: 'Applied through company website, great benefits package',
    appliedDate: '2025-01-20',
    createdAt: '2025-01-20T08:30:00Z',
    updatedAt: '2025-01-20T08:30:00Z',
  },
  {
    id: '9',
    userId: '1',
    companyName: 'Bosch',
    positionTitle: 'Software Engineer',
    location: 'Stuttgart',
    jobUrl: 'https://linkedin.com/jobs/606',
    salaryRange: '62000-82000',
    techStack: 'C++, Qt, Embedded Systems',
    status: 'Final Round',
    visaSponsorship: true,
    germanRequirement: 'Fluent',
    relocationSupport: true,
    jobBoardSource: 'LinkedIn',
    priorityStars: 5,
    notes: 'Final interview with CTO scheduled for next week',
    appliedDate: '2024-12-15',
    createdAt: '2024-12-15T13:45:00Z',
    updatedAt: '2025-01-18T11:20:00Z',
  },
  {
    id: '10',
    userId: '1',
    companyName: 'Merck',
    positionTitle: 'Data Scientist',
    location: 'Darmstadt',
    jobUrl: 'https://xing.com/jobs/707',
    salaryRange: '65000-85000',
    techStack: 'Python, TensorFlow, SQL',
    status: 'Offer',
    visaSponsorship: true,
    germanRequirement: 'None',
    relocationSupport: false,
    jobBoardSource: 'Xing',
    priorityStars: 4,
    notes: 'Received offer! Currently in negotiation phase.',
    appliedDate: '2024-12-20',
    createdAt: '2024-12-20T10:15:00Z',
    updatedAt: '2025-01-22T10:45:00Z',
  },
  // More recent applications (January 2025)
  {
    id: '11',
    userId: '1',
    companyName: 'Deutsche Telekom',
    positionTitle: 'Frontend Developer',
    location: 'Berlin',
    jobUrl: 'https://xing.com/jobs/808',
    salaryRange: '55000-75000',
    techStack: 'Vue.js, JavaScript, CSS',
    status: 'Ghosted',
    visaSponsorship: true,
    germanRequirement: 'Basic',
    relocationSupport: false,
    jobBoardSource: 'Xing',
    priorityStars: 3,
    appliedDate: '2025-01-14',
    createdAt: '2025-01-14T09:15:00Z',
    updatedAt: '2025-01-14T09:15:00Z',
  },
  {
    id: '12',
    userId: '1',
    companyName: 'Mercedes-Benz',
    positionTitle: 'Software Engineer',
    location: 'Stuttgart',
    jobUrl: 'https://linkedin.com/jobs/909',
    salaryRange: '65000-85000',
    techStack: 'C#, .NET, Azure',
    status: 'Applied',
    visaSponsorship: true,
    germanRequirement: 'Fluent',
    relocationSupport: true,
    jobBoardSource: 'LinkedIn',
    priorityStars: 4,
    appliedDate: '2025-01-16',
    createdAt: '2025-01-16T11:30:00Z',
    updatedAt: '2025-01-16T11:30:00Z',
  },
  {
    id: '13',
    userId: '1',
    companyName: 'Adidas',
    positionTitle: 'Full Stack Developer',
    location: 'Herzogenaurach',
    jobUrl: 'https://company-website.com/jobs/1010',
    salaryRange: '60000-80000',
    techStack: 'React, Node.js, GraphQL',
    status: 'Rejected',
    visaSponsorship: true,
    germanRequirement: 'Basic',
    relocationSupport: false,
    jobBoardSource: 'Company Website',
    priorityStars: 3,
    notes: 'Rejected after phone screen - role filled internally',
    appliedDate: '2025-01-08',
    createdAt: '2025-01-08T13:20:00Z',
    updatedAt: '2025-01-15T10:30:00Z',
  },
  {
    id: '14',
    userId: '1',
    companyName: 'Porsche',
    positionTitle: 'Backend Developer',
    location: 'Stuttgart',
    jobUrl: 'https://stepstone.de/jobs/1111',
    salaryRange: '65000-85000',
    techStack: 'Go, Kubernetes, PostgreSQL',
    status: 'Technical Round 1',
    visaSponsorship: true,
    germanRequirement: 'None',
    relocationSupport: true,
    jobBoardSource: 'StepStone',
    priorityStars: 5,
    notes: 'Exciting automotive tech role',
    appliedDate: '2025-01-11',
    createdAt: '2025-01-11T14:45:00Z',
    updatedAt: '2025-01-17T16:20:00Z',
  },
  {
    id: '15',
    userId: '1',
    companyName: 'Allianz',
    positionTitle: 'Data Engineer',
    location: 'Munich',
    jobUrl: 'https://indeed.de/jobs/1212',
    salaryRange: '60000-80000',
    techStack: 'Python, Spark, Snowflake',
    status: 'Applied',
    visaSponsorship: true,
    germanRequirement: 'Basic',
    relocationSupport: false,
    jobBoardSource: 'Indeed',
    priorityStars: 4,
    appliedDate: '2025-01-19',
    createdAt: '2025-01-19T10:00:00Z',
    updatedAt: '2025-01-19T10:00:00Z',
  },
  // December 2024 applications
  {
    id: '16',
    userId: '1',
    companyName: 'BASF',
    positionTitle: 'DevOps Engineer',
    location: 'Ludwigshafen',
    jobUrl: 'https://xing.com/jobs/1313',
    salaryRange: '65000-85000',
    techStack: 'AWS, Terraform, Jenkins',
    status: 'Ghosted',
    visaSponsorship: true,
    germanRequirement: 'Fluent',
    relocationSupport: true,
    jobBoardSource: 'Xing',
    priorityStars: 4,
    appliedDate: '2024-12-10',
    createdAt: '2024-12-10T08:30:00Z',
    updatedAt: '2024-12-10T08:30:00Z',
  },
  {
    id: '17',
    userId: '1',
    companyName: 'ThyssenKrupp',
    positionTitle: 'Software Developer',
    location: 'Duisburg',
    jobUrl: 'https://linkedin.com/jobs/1414',
    salaryRange: '55000-75000',
    techStack: 'Java, Spring, Oracle',
    status: 'Rejected',
    visaSponsorship: false,
    germanRequirement: 'Basic',
    relocationSupport: false,
    jobBoardSource: 'LinkedIn',
    priorityStars: 2,
    notes: 'Rejected after application review',
    appliedDate: '2024-12-08',
    createdAt: '2024-12-08T12:15:00Z',
    updatedAt: '2024-12-18T09:45:00Z',
  },
  {
    id: '18',
    userId: '1',
    companyName: 'Lufthansa',
    positionTitle: 'Full Stack Developer',
    location: 'Frankfurt',
    jobUrl: 'https://company-website.com/careers/1515',
    salaryRange: '62000-82000',
    techStack: 'Angular, Java, MySQL',
    status: 'Phone Screen',
    visaSponsorship: true,
    germanRequirement: 'Basic',
    relocationSupport: true,
    jobBoardSource: 'Company Website',
    priorityStars: 4,
    notes: 'Aviation industry - exciting domain',
    appliedDate: '2024-12-12',
    createdAt: '2024-12-12T15:30:00Z',
    updatedAt: '2024-12-16T11:00:00Z',
  },
  {
    id: '19',
    userId: '1',
    companyName: 'Continental',
    positionTitle: 'Embedded Software Engineer',
    location: 'Hanover',
    jobUrl: 'https://stepstone.de/jobs/1616',
    salaryRange: '65000-85000',
    techStack: 'C, C++, Automotive',
    status: 'Applied',
    visaSponsorship: true,
    germanRequirement: 'None',
    relocationSupport: false,
    jobBoardSource: 'StepStone',
    priorityStars: 3,
    appliedDate: '2024-12-14',
    createdAt: '2024-12-14T10:45:00Z',
    updatedAt: '2024-12-14T10:45:00Z',
  },
  {
    id: '20',
    userId: '1',
    companyName: 'Henkel',
    positionTitle: 'Frontend Developer',
    location: 'Düsseldorf',
    jobUrl: 'https://xing.com/jobs/1717',
    salaryRange: '58000-78000',
    techStack: 'React, TypeScript, SCSS',
    status: 'Replied',
    visaSponsorship: true,
    germanRequirement: 'Basic',
    relocationSupport: false,
    jobBoardSource: 'Xing',
    priorityStars: 3,
    notes: 'Consumer goods company - good work culture',
    appliedDate: '2024-12-16',
    createdAt: '2024-12-16T14:20:00Z',
    updatedAt: '2024-12-19T16:30:00Z',
  },
  // November 2024 applications
  {
    id: '21',
    userId: '1',
    companyName: 'RWE',
    positionTitle: 'Cloud Engineer',
    location: 'Essen',
    jobUrl: 'https://indeed.de/jobs/1818',
    salaryRange: '63000-83000',
    techStack: 'AWS, Terraform, Python',
    status: 'Ghosted',
    visaSponsorship: true,
    germanRequirement: 'None',
    relocationSupport: false,
    jobBoardSource: 'Indeed',
    priorityStars: 4,
    appliedDate: '2024-11-20',
    createdAt: '2024-11-20T09:15:00Z',
    updatedAt: '2024-11-20T09:15:00Z',
  },
  {
    id: '22',
    userId: '1',
    companyName: 'EDEKA',
    positionTitle: 'Software Developer',
    location: 'Hamburg',
    jobUrl: 'https://company-website.com/jobs/1919',
    salaryRange: '55000-75000',
    techStack: 'Java, Microservices, Docker',
    status: 'Rejected',
    visaSponsorship: true,
    germanRequirement: 'Fluent',
    relocationSupport: false,
    jobBoardSource: 'Company Website',
    priorityStars: 2,
    notes: 'Retail industry - language requirements too high',
    appliedDate: '2024-11-15',
    createdAt: '2024-11-15T11:00:00Z',
    updatedAt: '2024-11-25T14:20:00Z',
  },
  {
    id: '23',
    userId: '1',
    companyName: 'Otto Group',
    positionTitle: 'Backend Developer',
    location: 'Hamburg',
    jobUrl: 'https://xing.com/jobs/2020',
    salaryRange: '60000-80000',
    techStack: 'Scala, Akka, Kafka',
    status: 'Technical Round 1',
    visaSponsorship: true,
    germanRequirement: 'Basic',
    relocationSupport: true,
    jobBoardSource: 'Xing',
    priorityStars: 4,
    notes: 'E-commerce giant - strong tech culture',
    appliedDate: '2024-11-18',
    createdAt: '2024-11-18T13:45:00Z',
    updatedAt: '2024-11-28T10:15:00Z',
  },
  {
    id: '24',
    userId: '1',
    companyName: 'Fresenius',
    positionTitle: 'Data Scientist',
    location: 'Bad Homburg',
    jobUrl: 'https://linkedin.com/jobs/2121',
    salaryRange: '65000-85000',
    techStack: 'R, Python, Healthcare Data',
    status: 'Applied',
    visaSponsorship: true,
    germanRequirement: 'None',
    relocationSupport: false,
    jobBoardSource: 'LinkedIn',
    priorityStars: 3,
    appliedDate: '2024-11-22',
    createdAt: '2024-11-22T15:30:00Z',
    updatedAt: '2024-11-22T15:30:00Z',
  },
  {
    id: '25',
    userId: '1',
    companyName: 'Schneider Electric',
    positionTitle: 'IoT Developer',
    location: 'Ratingen',
    jobUrl: 'https://stepstone.de/jobs/2222',
    salaryRange: '62000-82000',
    techStack: 'Python, IoT, MQTT',
    status: 'Ghosted',
    visaSponsorship: true,
    germanRequirement: 'Basic',
    relocationSupport: true,
    jobBoardSource: 'StepStone',
    priorityStars: 4,
    appliedDate: '2024-11-25',
    createdAt: '2024-11-25T10:00:00Z',
    updatedAt: '2024-11-25T10:00:00Z',
  },
  // October 2024 applications
  {
    id: '26',
    userId: '1',
    companyName: 'DHL',
    positionTitle: 'Software Engineer',
    location: 'Bonn',
    jobUrl: 'https://indeed.de/jobs/2323',
    salaryRange: '58000-78000',
    techStack: 'Java, Logistics, APIs',
    status: 'Rejected',
    visaSponsorship: true,
    germanRequirement: 'Fluent',
    relocationSupport: false,
    jobBoardSource: 'Indeed',
    priorityStars: 3,
    notes: 'Logistics domain - German fluency required',
    appliedDate: '2024-10-15',
    createdAt: '2024-10-15T12:30:00Z',
    updatedAt: '2024-10-25T09:45:00Z',
  },
  {
    id: '27',
    userId: '1',
    companyName: 'Infineon',
    positionTitle: 'Embedded Engineer',
    location: 'Munich',
    jobUrl: 'https://xing.com/jobs/2424',
    salaryRange: '65000-85000',
    techStack: 'C, Embedded Linux, IoT',
    status: 'Phone Screen',
    visaSponsorship: true,
    germanRequirement: 'None',
    relocationSupport: true,
    jobBoardSource: 'Xing',
    priorityStars: 5,
    notes: 'Semiconductor industry - cutting-edge tech',
    appliedDate: '2024-10-18',
    createdAt: '2024-10-18T14:15:00Z',
    updatedAt: '2024-10-22T11:30:00Z',
  },
  {
    id: '28',
    userId: '1',
    companyName: 'DATEV',
    positionTitle: 'Full Stack Developer',
    location: 'Nuremberg',
    jobUrl: 'https://company-website.com/jobs/2525',
    salaryRange: '60000-80000',
    techStack: 'C#, ASP.NET, SQL Server',
    status: 'Applied',
    visaSponsorship: false,
    germanRequirement: 'Fluent',
    relocationSupport: false,
    jobBoardSource: 'Company Website',
    priorityStars: 4,
    notes: 'Accounting software - German market focus',
    appliedDate: '2024-10-20',
    createdAt: '2024-10-20T09:00:00Z',
    updatedAt: '2024-10-20T09:00:00Z',
  },
  {
    id: '29',
    userId: '1',
    companyName: 'Walmart (Germany)',
    positionTitle: 'Frontend Developer',
    location: 'Berlin',
    jobUrl: 'https://linkedin.com/jobs/2626',
    salaryRange: '55000-75000',
    techStack: 'React, Redux, Node.js',
    status: 'Replied',
    visaSponsorship: true,
    germanRequirement: 'Basic',
    relocationSupport: false,
    jobBoardSource: 'LinkedIn',
    priorityStars: 3,
    notes: 'International retail - good benefits',
    appliedDate: '2024-10-22',
    createdAt: '2024-10-22T13:45:00Z',
    updatedAt: '2024-10-25T15:20:00Z',
  },
  {
    id: '30',
    userId: '1',
    companyName: 'KPMG',
    positionTitle: 'Data Analyst',
    location: 'Frankfurt',
    jobUrl: 'https://stepstone.de/jobs/2727',
    salaryRange: '58000-78000',
    techStack: 'Python, SQL, Tableau',
    status: 'Ghosted',
    visaSponsorship: true,
    germanRequirement: 'Fluent',
    relocationSupport: true,
    jobBoardSource: 'StepStone',
    priorityStars: 3,
    appliedDate: '2024-10-25',
    createdAt: '2024-10-25T11:15:00Z',
    updatedAt: '2024-10-25T11:15:00Z',
  },
  // September 2024 applications
  {
    id: '31',
    userId: '1',
    companyName: 'Deloitte',
    positionTitle: 'Technology Consultant',
    location: 'Munich',
    jobUrl: 'https://xing.com/jobs/2828',
    salaryRange: '65000-85000',
    techStack: 'Cloud, Azure, Consulting',
    status: 'Rejected',
    visaSponsorship: true,
    germanRequirement: 'Fluent',
    relocationSupport: false,
    jobBoardSource: 'Xing',
    priorityStars: 4,
    notes: 'Consulting firm - high German requirements',
    appliedDate: '2024-09-15',
    createdAt: '2024-09-15T10:30:00Z',
    updatedAt: '2024-09-25T14:00:00Z',
  },
  {
    id: '32',
    userId: '1',
    companyName: 'Accenture',
    positionTitle: 'Software Developer',
    location: 'Berlin',
    jobUrl: 'https://indeed.de/jobs/2929',
    salaryRange: '62000-82000',
    techStack: 'Java, Spring, AWS',
    status: 'Technical Round 1',
    visaSponsorship: true,
    germanRequirement: 'Basic',
    relocationSupport: true,
    jobBoardSource: 'Indeed',
    priorityStars: 4,
    notes: 'Global consulting - good learning opportunities',
    appliedDate: '2024-09-18',
    createdAt: '2024-09-18T12:45:00Z',
    updatedAt: '2024-09-28T16:30:00Z',
  },
  {
    id: '33',
    userId: '1',
    companyName: 'Capgemini',
    positionTitle: 'DevOps Engineer',
    location: 'Hamburg',
    jobUrl: 'https://linkedin.com/jobs/3030',
    salaryRange: '60000-80000',
    techStack: 'Docker, Kubernetes, Jenkins',
    status: 'Applied',
    visaSponsorship: true,
    germanRequirement: 'None',
    relocationSupport: false,
    jobBoardSource: 'LinkedIn',
    priorityStars: 3,
    appliedDate: '2024-09-20',
    createdAt: '2024-09-20T09:15:00Z',
    updatedAt: '2024-09-20T09:15:00Z',
  },
  {
    id: '34',
    userId: '1',
    companyName: 'T-Systems',
    positionTitle: 'Cloud Architect',
    location: 'Frankfurt',
    jobUrl: 'https://stepstone.de/jobs/3131',
    salaryRange: '70000-90000',
    techStack: 'AWS, Azure, Terraform',
    status: 'Ghosted',
    visaSponsorship: true,
    germanRequirement: 'Basic',
    relocationSupport: true,
    jobBoardSource: 'StepStone',
    priorityStars: 5,
    notes: 'Telekom subsidiary - enterprise focus',
    appliedDate: '2024-09-22',
    createdAt: '2024-09-22T14:00:00Z',
    updatedAt: '2024-09-22T14:00:00Z',
  },
  {
    id: '35',
    userId: '1',
    companyName: 'ZF Friedrichshafen',
    positionTitle: 'Automotive Software Engineer',
    location: 'Friedrichshafen',
    jobUrl: 'https://xing.com/jobs/3232',
    salaryRange: '65000-85000',
    techStack: 'C++, AUTOSAR, CAN Bus',
    status: 'Replied',
    visaSponsorship: true,
    germanRequirement: 'Fluent',
    relocationSupport: true,
    jobBoardSource: 'Xing',
    priorityStars: 4,
    notes: 'Automotive supplier - strong in embedded systems',
    appliedDate: '2024-09-25',
    createdAt: '2024-09-25T11:30:00Z',
    updatedAt: '2024-09-28T13:45:00Z',
  },
  // August 2024 applications
  {
    id: '36',
    userId: '1',
    companyName: 'MAN Truck & Bus',
    positionTitle: 'Software Developer',
    location: 'Munich',
    jobUrl: 'https://company-website.com/jobs/3333',
    salaryRange: '60000-80000',
    techStack: 'C#, .NET, Vehicle Systems',
    status: 'Rejected',
    visaSponsorship: false,
    germanRequirement: 'Fluent',
    relocationSupport: false,
    jobBoardSource: 'Company Website',
    priorityStars: 2,
    notes: 'Commercial vehicles - German fluency essential',
    appliedDate: '2024-08-15',
    createdAt: '2024-08-15T10:00:00Z',
    updatedAt: '2024-08-25T12:30:00Z',
  },
  {
    id: '37',
    userId: '1',
    companyName: 'Fraport',
    positionTitle: 'Data Engineer',
    location: 'Frankfurt',
    jobUrl: 'https://indeed.de/jobs/3434',
    salaryRange: '62000-82000',
    techStack: 'Python, Big Data, Airport Systems',
    status: 'Phone Screen',
    visaSponsorship: true,
    germanRequirement: 'Basic',
    relocationSupport: false,
    jobBoardSource: 'Indeed',
    priorityStars: 3,
    notes: 'Airport authority - interesting domain',
    appliedDate: '2024-08-18',
    createdAt: '2024-08-18T13:15:00Z',
    updatedAt: '2024-08-22T15:45:00Z',
  },
  {
    id: '38',
    userId: '1',
    companyName: 'Roche Diagnostics',
    positionTitle: 'Bioinformatics Engineer',
    location: 'Mannheim',
    jobUrl: 'https://linkedin.com/jobs/3535',
    salaryRange: '65000-85000',
    techStack: 'Python, R, Genomics',
    status: 'Applied',
    visaSponsorship: true,
    germanRequirement: 'None',
    relocationSupport: true,
    jobBoardSource: 'LinkedIn',
    priorityStars: 4,
    appliedDate: '2024-08-20',
    createdAt: '2024-08-20T09:30:00Z',
    updatedAt: '2024-08-20T09:30:00Z',
  },
  {
    id: '39',
    userId: '1',
    companyName: 'EnBW',
    positionTitle: 'Renewable Energy Software Engineer',
    location: 'Stuttgart',
    jobUrl: 'https://xing.com/jobs/3636',
    salaryRange: '63000-83000',
    techStack: 'Python, IoT, Energy Systems',
    status: 'Ghosted',
    visaSponsorship: true,
    germanRequirement: 'Basic',
    relocationSupport: false,
    jobBoardSource: 'Xing',
    priorityStars: 4,
    notes: 'Energy sector - sustainable tech focus',
    appliedDate: '2024-08-22',
    createdAt: '2024-08-22T14:45:00Z',
    updatedAt: '2024-08-22T14:45:00Z',
  },
  {
    id: '40',
    userId: '1',
    companyName: 'HelloFresh',
    positionTitle: 'Backend Developer',
    location: 'Berlin',
    jobUrl: 'https://stepstone.de/jobs/3737',
    salaryRange: '60000-80000',
    techStack: 'Go, Microservices, Kubernetes',
    status: 'Technical Round 1',
    visaSponsorship: true,
    germanRequirement: 'None',
    relocationSupport: false,
    jobBoardSource: 'StepStone',
    priorityStars: 4,
    notes: 'Food delivery startup - fast-paced environment',
    appliedDate: '2024-08-25',
    createdAt: '2024-08-25T11:00:00Z',
    updatedAt: '2024-09-02T10:30:00Z',
  },
  // July 2024 applications
  {
    id: '41',
    userId: '1',
    companyName: 'N26',
    positionTitle: 'Mobile Developer',
    location: 'Berlin',
    jobUrl: 'https://company-website.com/jobs/3838',
    salaryRange: '65000-85000',
    techStack: 'React Native, iOS, Android',
    status: 'Rejected',
    visaSponsorship: true,
    germanRequirement: 'Basic',
    relocationSupport: false,
    jobBoardSource: 'Company Website',
    priorityStars: 5,
    notes: 'Fintech startup - rejected due to mobile focus mismatch',
    appliedDate: '2024-07-15',
    createdAt: '2024-07-15T12:30:00Z',
    updatedAt: '2024-07-25T09:15:00Z',
  },
  {
    id: '42',
    userId: '1',
    companyName: 'Trade Republic',
    positionTitle: 'Frontend Developer',
    location: 'Berlin',
    jobUrl: 'https://xing.com/jobs/3939',
    salaryRange: '62000-82000',
    techStack: 'React, TypeScript, WebSockets',
    status: 'Phone Screen',
    visaSponsorship: true,
    germanRequirement: 'None',
    relocationSupport: false,
    jobBoardSource: 'Xing',
    priorityStars: 5,
    notes: 'Neo-broker - innovative fintech',
    appliedDate: '2024-07-18',
    createdAt: '2024-07-18T10:45:00Z',
    updatedAt: '2024-07-22T14:20:00Z',
  },
  {
    id: '43',
    userId: '1',
    companyName: 'Auto1',
    positionTitle: 'Data Scientist',
    location: 'Berlin',
    jobUrl: 'https://linkedin.com/jobs/4040',
    salaryRange: '65000-85000',
    techStack: 'Python, ML, Automotive Data',
    status: 'Applied',
    visaSponsorship: true,
    germanRequirement: 'Basic',
    relocationSupport: true,
    jobBoardSource: 'LinkedIn',
    priorityStars: 4,
    appliedDate: '2024-07-20',
    createdAt: '2024-07-20T13:15:00Z',
    updatedAt: '2024-07-20T13:15:00Z',
  },
  {
    id: '44',
    userId: '1',
    companyName: 'Sennder',
    positionTitle: 'Backend Engineer',
    location: 'Berlin',
    jobUrl: 'https://indeed.de/jobs/4141',
    salaryRange: '63000-83000',
    techStack: 'Python, Django, PostgreSQL',
    status: 'Ghosted',
    visaSponsorship: true,
    germanRequirement: 'None',
    relocationSupport: false,
    jobBoardSource: 'Indeed',
    priorityStars: 4,
    notes: 'Logistics tech - digital freight forwarding',
    appliedDate: '2024-07-22',
    createdAt: '2024-07-22T15:30:00Z',
    updatedAt: '2024-07-22T15:30:00Z',
  },
  {
    id: '45',
    userId: '1',
    companyName: 'Tier Mobility',
    positionTitle: 'Full Stack Developer',
    location: 'Berlin',
    jobUrl: 'https://stepstone.de/jobs/4242',
    salaryRange: '60000-80000',
    techStack: 'React, Node.js, MongoDB',
    status: 'Replied',
    visaSponsorship: true,
    germanRequirement: 'Basic',
    relocationSupport: true,
    jobBoardSource: 'StepStone',
    priorityStars: 3,
    notes: 'Scooter sharing - mobility solutions',
    appliedDate: '2024-07-25',
    createdAt: '2024-07-25T11:45:00Z',
    updatedAt: '2024-07-28T13:00:00Z',
  },
  // June 2024 applications
  {
    id: '46',
    userId: '1',
    companyName: 'Gorillas',
    positionTitle: 'Software Engineer',
    location: 'Berlin',
    jobUrl: 'https://xing.com/jobs/4343',
    salaryRange: '62000-82000',
    techStack: 'Go, React, Kubernetes',
    status: 'Rejected',
    visaSponsorship: true,
    germanRequirement: 'Basic',
    relocationSupport: false,
    jobBoardSource: 'Xing',
    priorityStars: 4,
    notes: 'Quick commerce - fast growth but high competition',
    appliedDate: '2024-06-15',
    createdAt: '2024-06-15T09:00:00Z',
    updatedAt: '2024-06-25T12:30:00Z',
  },
  {
    id: '47',
    userId: '1',
    companyName: 'FlixBus',
    positionTitle: 'Data Engineer',
    location: 'Munich',
    jobUrl: 'https://company-website.com/jobs/4444',
    salaryRange: '60000-80000',
    techStack: 'Python, Airflow, BigQuery',
    status: 'Technical Round 1',
    visaSponsorship: true,
    germanRequirement: 'None',
    relocationSupport: true,
    jobBoardSource: 'Company Website',
    priorityStars: 3,
    notes: 'Intercity bus service - transportation data',
    appliedDate: '2024-06-18',
    createdAt: '2024-06-18T14:30:00Z',
    updatedAt: '2024-06-28T10:45:00Z',
  },
  {
    id: '48',
    userId: '1',
    companyName: 'GetYourGuide',
    positionTitle: 'Frontend Developer',
    location: 'Berlin',
    jobUrl: 'https://linkedin.com/jobs/4545',
    salaryRange: '58000-78000',
    techStack: 'Vue.js, Nuxt.js, TypeScript',
    status: 'Applied',
    visaSponsorship: true,
    germanRequirement: 'Basic',
    relocationSupport: false,
    jobBoardSource: 'LinkedIn',
    priorityStars: 3,
    appliedDate: '2024-06-20',
    createdAt: '2024-06-20T11:15:00Z',
    updatedAt: '2024-06-20T11:15:00Z',
  },
  {
    id: '49',
    userId: '1',
    companyName: 'SumUp',
    positionTitle: 'Mobile Developer',
    location: 'Berlin',
    jobUrl: 'https://stepstone.de/jobs/4646',
    salaryRange: '65000-85000',
    techStack: 'Flutter, Dart, Firebase',
    status: 'Ghosted',
    visaSponsorship: true,
    germanRequirement: 'None',
    relocationSupport: false,
    jobBoardSource: 'StepStone',
    priorityStars: 4,
    notes: 'Payment processing - fintech focus',
    appliedDate: '2024-06-22',
    createdAt: '2024-06-22T13:00:00Z',
    updatedAt: '2024-06-22T13:00:00Z',
  },
  {
    id: '50',
    userId: '1',
    companyName: 'ResearchGate',
    positionTitle: 'Backend Developer',
    location: 'Berlin',
    jobUrl: 'https://xing.com/jobs/4747',
    salaryRange: '62000-82000',
    techStack: 'Ruby on Rails, PostgreSQL, Elasticsearch',
    status: 'Phone Screen',
    visaSponsorship: true,
    germanRequirement: 'Basic',
    relocationSupport: true,
    jobBoardSource: 'Xing',
    priorityStars: 4,
    notes: 'Academic research platform - meaningful work',
    appliedDate: '2024-06-25',
    createdAt: '2024-06-25T15:45:00Z',
    updatedAt: '2024-06-29T11:20:00Z',
  }
];

export const mockContacts: NetworkContact[] = [
  {
    id: '1',
    userId: '1',
    name: 'Rajesh Kumar',
    email: 'rajesh@example.com',
    company: 'SAP',
    relationship: 'Former colleague',
    connectionStrength: 5,
    lastContactDate: '2025-01-10',
    notes: 'Can provide referral for full-stack positions. Very supportive and well-connected in the Berlin tech scene.',
  },
  {
    id: '2',
    userId: '1',
    name: 'Anna Schmidt',
    email: 'anna.schmidt@siemens.com',
    company: 'Siemens',
    relationship: 'LinkedIn Connection',
    connectionStrength: 4,
    lastContactDate: '2025-01-15',
    notes: 'HR Manager at Siemens Munich. Reached out about backend developer positions.',
    applicationId: '2'
  },
  {
    id: '3',
    userId: '1',
    name: 'Michael Weber',
    email: 'michael.weber@google.com',
    company: 'Google',
    relationship: 'Mentor',
    connectionStrength: 5,
    lastContactDate: '2024-12-20',
    notes: 'Senior engineer at Google Munich. Provides excellent career advice and interview tips.',
  },
  {
    id: '4',
    userId: '1',
    name: 'Lisa Mueller',
    email: 'lisa.mueller@startup.de',
    company: 'TechStartup GmbH',
    relationship: 'Conference Contact',
    connectionStrength: 3,
    lastContactDate: '2024-11-28',
    notes: 'Met at WebDev Conference Berlin 2024. Interested in junior developers with German skills.',
  },
  {
    id: '5',
    userId: '1',
    name: 'Thomas Bauer',
    email: 'thomas.bauer@bmw.de',
    company: 'BMW',
    relationship: 'Alumni',
    connectionStrength: 4,
    lastContactDate: '2025-01-05',
    notes: 'BITS Pilani alumni working in automotive software. Can help with networking in Munich.',
  },
  {
    id: '6',
    userId: '1',
    name: 'Sarah Johnson',
    company: 'Microsoft',
    relationship: 'Current Colleague',
    connectionStrength: 4,
    lastContactDate: '2025-01-18',
    notes: 'Works in the same team. Great for internal referrals and technical discussions.',
  },
  {
    id: '7',
    userId: '1',
    name: 'David Chen',
    email: 'david.chen@freelancer.net',
    relationship: 'Industry Contact',
    connectionStrength: 2,
    lastContactDate: '2024-10-15',
    notes: 'Freelance developer. Occasional project collaborations. Not very active on LinkedIn.',
  },
  {
    id: '8',
    userId: '1',
    name: 'Maria Garcia',
    email: 'maria.garcia@telekom.de',
    company: 'Deutsche Telekom',
    relationship: 'Referral Source',
    connectionStrength: 4,
    lastContactDate: '2024-12-10',
    notes: 'Provided referral for a position at Telekom. Very helpful and responsive.',
    applicationId: '1'
  },
];

export const mockDailyGoals: DailyGoal[] = [
  {
    id: '1',
    userId: '1',
    date: new Date().toISOString().split('T')[0],
    goalType: 'Apply to jobs',
    targetCount: 5,
    currentCount: 3,
    completed: false,
  },
  {
    id: '2',
    userId: '1',
    date: new Date().toISOString().split('T')[0],
    goalType: 'Follow up on applications',
    targetCount: 3,
    currentCount: 1,
    completed: false,
  },
  {
    id: '3',
    userId: '1',
    date: new Date().toISOString().split('T')[0],
    goalType: 'Add networking contacts',
    targetCount: 2,
    currentCount: 2,
    completed: true,
  },
];